version: '3'
services:
  main:
    build:
      context: ../../../
      dockerfile: Dockerfile-dev
    image: '${COMPOSE_PROJECT_NAME}-service:latest'
    container_name: '${COMPOSE_PROJECT_NAME}-service'
    ports:
      - '${PORT-8101}:80'
      - '${DEBUG_PORT-8100}:${DEBUG_PORT-8100}'
    restart: ${AUTO_RESTART}
    command: ${CUSTOM_CMD}
    environment:
      - NODE_ENV=development
      - PORT=80
    volumes:
      - ./wait-for-it.sh:/ebsa/service/wait-for-it.sh
      - ../../../index.js:/ebsa/service/index.js
      - ../../../.babelrc:/ebsa/service/.babelrc
      - ../../../env.config:/ebsa/service/env.config
      - ../../../package.json:/ebsa/service/package.json
      - ../../../yarn.lock:/ebsa/service/yarn.lock
      - ../../../server:/ebsa/service/server
      - ../../../configs:/ebsa/service/configs
      - ../../../data:/ebsa/service/data
    depends_on:
      - 'redis'
      - 'mongoimport'
      - 'mysql'
  redis:
    image: 'redis:latest'
    container_name: '${COMPOSE_PROJECT_NAME}-redis'
    ports:
      - '${REDIS_PORT-6379}:6379'
  mongo:
    image: 'mongo:3.2'
    container_name: '${COMPOSE_PROJECT_NAME}-mongo'
    ports:
      - '${MONGO_PORT-27017}:27017'
  mongoimport:
    build:
      context: ../../../
      dockerfile: configs/Dockerfile-mongoimport
    image: '${COMPOSE_PROJECT_NAME}-mongoimport:latest'
    container_name: '${COMPOSE_PROJECT_NAME}-mongoimport'
    depends_on:
      - 'mongo'
  mysql:
    image: 'mysql:5.6'
    container_name: '${COMPOSE_PROJECT_NAME}-mysql'
    ports:
      - '${MYSQL_PORT-3306}:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=default
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/encoding.cnf
      - ../../../data/mysql:/docker-entrypoint-initdb.d
