
# FROM node:7.8
FROM node:7.8-alpine

# install yarn
# for unbuntu
# https://github.com/yarnpkg/yarn/blob/master/Dockerfile.node7
# ADD https://dl.yarnpkg.com/debian/pubkey.gpg /tmp/yarn-pubkey.gpg
# RUN apt-key add /tmp/yarn-pubkey.gpg && rm /tmp/yarn-pubkey.gpg
# RUN echo "deb http://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
# RUN apt-get -y update && \
#   apt-get install -y --no-install-recommends yarn && \
#   apt-get clean && \
#   rm -rf /var/lib/apt/lists/*
# for alpine
# https://github.com/yarnpkg/yarn/issues/1326
ENV YARN_VERSION 0.22.0
ADD https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v${YARN_VERSION}.tar.gz /opt/yarn.tar.gz
RUN yarnDirectory=/opt/yarn && \
    mkdir -p "$yarnDirectory" && \
    tar -xzf /opt/yarn.tar.gz -C "$yarnDirectory" && \
    ln -s "$yarnDirectory/dist/bin/yarn" /usr/local/bin/ && \
    rm /opt/yarn.tar.gz

# for unbuntu
# RUN echo "Asia/Shanghai" > /etc/timezone
# RUN dpkg-reconfigure -f noninteractive tzdata
# for alpine
RUN apk update && apk add ca-certificates && \
    apk add tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

# for China
ENV NODEJS_ORG_MIRROR="http://npm.taobao.org/mirrors/node"
ENV SASS_BINARY_SITE="https://npm.taobao.org/mirrors/node-sass"
ENV PHANTOMJS_CDNURL="http://npm.taobao.org/mirrors/phantomjs"
ENV ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"
ENV CHROMEDRIVER_CDNURL="http://npm.taobao.org/mirrors/chromedriver"
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org

RUN mkdir -p /ebsa/service \
  && mkdir -p /tmp/service \
  && mkdir -p /int/www \
  && touch /int/www/stats.html

# for npm install
# ADD package.json /tmp/service/
# RUN cd /tmp/service && NODE_ENV=development cnpm install
# WORKDIR /ebsa/service
# RUN ln -s /tmp/service/node_modules
# for yarn
ADD package.json yarn.lock /tmp/service/
RUN cd /tmp/service && NODE_ENV=development yarn
WORKDIR /ebsa/service
RUN ln -s /tmp/service/node_modules

COPY . /ebsa/service

EXPOSE 80
CMD ["npm", "run", "start"]
